name: update
on:
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3.0.0
      - name: Fabric Update
        uses: JamCoreModding/FabricUpdateAction@1.0.3
        with:
          game-version: 1.18.2
